name: Build and publish docker image

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 5 * * *" # schedule a docker build everyday at 5 AM
  workflow_dispatch:

env:
  IMAGE_NAME: wtfd

jobs:
  docker_build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username joelazar --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=${{ github.repository }}
          VERSION=latest
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
